# Generated by Django 4.1.13 on 2024-09-18 00:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('urlName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Safe to Swim', 'Safe to Swim'), ('Unsafe to Swim', 'Unsafe to Swim')], max_length=20)),
                ('description', models.TextField()),
                ('current_temperature', models.FloatField(max_length=100)),
                ('current_rain', models.CharField(max_length=100)),
                ('current_wind_speed', models.FloatField(max_length=100)),
                ('saturday_temperature', models.FloatField(max_length=100)),
                ('saturday_rain', models.CharField(max_length=100)),
                ('saturday_wind_speed', models.FloatField(max_length=100)),
                ('sunday_temperature', models.FloatField(max_length=100)),
                ('sunday_rain', models.CharField(max_length=100)),
                ('sunday_wind_speed', models.FloatField(max_length=100)),
                ('picture', models.ImageField(upload_to='beach_pictures/')),
                ('funFacts', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('EducationalContent_id', models.AutoField(primary_key=True, serialize=False)),
                ('title1', models.CharField(max_length=100)),
                ('detail1', models.TextField()),
                ('title2', models.CharField(max_length=100)),
                ('detail2', models.TextField()),
                ('source', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('source', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.beach')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('coordinateLat', models.FloatField(max_length=100)),
                ('coordinateLong', models.FloatField(max_length=100)),
                ('beach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map', to='core.beach')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('beach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.beach')),
            ],
        ),
    ]
