# Generated by Django 3.0.5 on 2024-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('beach_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='beach_pictures/')),
                ('description', models.TextField()),
                ('fun_facts', models.TextField()),
            ],
        ),
    ]
