# Generated by Django 4.1.13 on 2024-08-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beach',
        ),
    ]
