# Generated by Django 4.1.13 on 2024-09-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('coordinateLat', models.FloatField(max_length=100)),
                ('coordinateLong', models.FloatField(max_length=100)),
                ('beach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map', to='core.beach')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='general_comment_section',
        ),
        migrations.AddField(
            model_name='comment',
            name='beach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.beach'),
        ),
        migrations.DeleteModel(
            name='GeneralCommentSection',
        ),
    ]
