# Generated by Django 4.1.13 on 2024-09-03 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Safe to Swim', 'Safe to Swim'), ('Unsafe to Swim', 'Unsafe to Swim')], max_length=20)),
                ('description', models.TextField()),
                ('current_temperature', models.FloatField(max_length=100)),
                ('current_rain', models.CharField(max_length=100)),
                ('current_wind_speed', models.FloatField(max_length=100)),
                ('saturday_temperature', models.FloatField(max_length=100)),
                ('saturday_rain', models.CharField(max_length=100)),
                ('saturday_wind_speed', models.FloatField(max_length=100)),
                ('sunday_temperature', models.FloatField(max_length=100)),
                ('sunday_rain', models.CharField(max_length=100)),
                ('sunday_wind_speed', models.FloatField(max_length=100)),
                ('busyness', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='beach_pictures/')),
                ('fun_facts', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralCommentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('source', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('crowd_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('comment', models.TextField()),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='coree.beach')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('beach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='coree.beach')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='coree.report')),
            ],
        ),
        migrations.CreateModel(
            name='CommentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_section', to='coree.beach')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coree.commentsection')),
                ('general_comment_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coree.generalcommentsection')),
            ],
        ),
    ]
